// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUqfT1Ld_xodZfaVyNQNM0DCTHmqngnl8',
    appId: '1:284919139346:web:fc94004778841300175ccb',
    messagingSenderId: '284919139346',
    projectId: 'mateapp-8a35b',
    authDomain: 'mateapp-8a35b.firebaseapp.com',
    storageBucket: 'mateapp-8a35b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDg7juF9D0Yx9qpeYVljSz2W0JDNOBm3Co',
    appId: '1:284919139346:android:e151fe864b2b3654175ccb',
    messagingSenderId: '284919139346',
    projectId: 'mateapp-8a35b',
    storageBucket: 'mateapp-8a35b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTOMC32h0i82P2ZFPLIV2uwacIq0c8S0U',
    appId: '1:284919139346:ios:30157380e092a3a6175ccb',
    messagingSenderId: '284919139346',
    projectId: 'mateapp-8a35b',
    storageBucket: 'mateapp-8a35b.appspot.com',
    iosBundleId: 'com.example.mateApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTOMC32h0i82P2ZFPLIV2uwacIq0c8S0U',
    appId: '1:284919139346:ios:30157380e092a3a6175ccb',
    messagingSenderId: '284919139346',
    projectId: 'mateapp-8a35b',
    storageBucket: 'mateapp-8a35b.appspot.com',
    iosBundleId: 'com.example.mateApp',
  );
}
